defaults:
  - _self_
  - trainer: defaults
  - optimizer: adam
  - lr_scheduler: inv_sqrt_w_linear_ramps
  - model: isotropic_model
  - data: all_2d
  - experiment: defaults
  - server: ???
  - distribution: local
  - logger: wandb
  - checkpoint: defaults
  - finetuning_mods: defaults
data_workers: 14
name: default_name
finetune: False
automatic_setup: True
