_target_: walrus.trainer.checkpoints.CheckPointer
save_dir: checkpoints/${name}
load_checkpoint_path: null # <path>/checkpoints/sharded_checkpoint_dir/
coalesced_checkpoint_path: null # <path>/checkpoints/coalesced.pth # Only specify load_checkpoint_path or coalesced_checkpoint_path - coalesced uses a single checkpoint assumed to be on CPU
save_best: True
checkpoint_frequency: 20
align_fields: True # Whether to align the fields in the checkpoint to the model, useful if there are new fields or the data is loaded in a different order
load_chkpt_after_finetuning_expansion: False # Whether to load the coalesced checkpoint after expanding the model for finetuning. If False, the checkpoint is loaded before expansion.
