defaults:
  - defaults
  - _self_

max_epoch: 1
val_frequency: 1
image_validation: False
video_validation: False
revin:
  _target_: walrus.trainer.normalization_strat.SamplewiseRevNormalization
  _partial_: True
