_target_: walrus.models.DPOTWrapper
img_size: 256
patch_size: 8
in_channels: 11
in_timesteps: 10
out_timesteps: 1
out_channels: 11
normalize: False
# use_ln: False
embed_dim: 1024
modes: 32
depth: 12
n_blocks: 8
mlp_ratio: 4
out_layer_dim: 32
act: gelu
n_cls: 1
load_checkpoint_path: "//mnt//home//mmccabe//projects//walrus//walrus//other_cpts//model_M.pth"
