_target_: walrus.models.MPPWrapper
patch_size: 16
embed_dim: 768
processor_blocks: 12
n_states: 80
num_heads: 12
drop_path: 0.1
load_checkpoint_path: /mnt/home/mmccabe/projects/multiple_physics_pretraining/pretrained_weights/MPP_AViT_B