_target_: walrus.models.ScOTWrapper
image_size: 512
patch_size: 4
num_channels: 5
num_out_channels: 5
embed_dim: 192
depths: [8, 8, 8, 8]
num_heads: [3, 6, 12, 24]
skip_connections: [2, 2, 2, 0]
window_size: 16
mlp_ratio: 4.0
qkv_bias: True
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0
drop_path_rate: 0.1
hidden_act: gelu
use_absolute_embeddings: False
initializer_range: 0.02
layer_norm_eps: 1e-5
p: 1  # for loss: 1 for l1, 2 for l2
channel_slice_list_normalized_loss: None #[0, 1, 2, 3]  # if None will fall back to absolute loss otherwise normalized loss with split channels
residual_model: convnext  # "convnext" or "resnet"
use_conditioning: True
learn_residual: False
use_mask_token: False
from_pretrained: L



# "encoder_stride": 32,
# "hidden_size": 768,
# "model_type": "swinv2",
# "num_layers": 4,
# "num_out_channels": 4,
# "out_features": [
#   "stage4"
# ],
# "out_indices": [
#   4
# ],
