_target_: torch.optim.AdamW
weight_decay: 1E-4
eps: 1e-10
lr: 1e-5

param_groups:
  - params: embed
    lr: 5e-5
  - params: debed
    lr: 5e-5
  - params: blocks
    lr: 1e-6
  - params: encoder_dummy
